/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import listaSimple.ListaUsuario;
import modelo.Archivos;
import modelo.Usuario;

/**
 *
 * @author LENOVO 14ALC6
 */
public class Registro extends javax.swing.JFrame {

    ListaUsuario lista = new ListaUsuario();
    //Login frmLogin = new Login();

    public Registro() {
        initComponents();
        this.setTitle("Registro");
        this.setSize(840, 660);
        this.setLocationRelativeTo(null);
        this.setBackground(new Color(197, 22, 244));
        this.setVisible(true);

        /*Usuario administrador = new Usuario(1, "Nubia", "nubia@gmail.com", "123456", "Administrador", "Activo");
        Usuario cliente = new Usuario(1, "Cliente", "cliente@gmail.com", "123456", "Cliente", "Activo");
        lista.setAddInicio(cliente);
        lista.setAddInicio(administrador);*/
        // Establecer imágenes en los JLabels
        SetImageLabel(Dog1, "src/Imagenes/huellita perro 1.png");
        SetImageLabel(Dog2, "src/Imagenes/huellita perro 2.png");
        SetImageLabel(Cat3, "src/Imagenes/huellita de gato 2.png");
        SetImageLabel(Cat3, "src/Imagenes/huellita gato 4.png");
        SetImageLabel(punto4, "src/Imagenes/punto 2.png");
        SetImageLabel(punto3, "src/Imagenes/punto 4.png");
        SetImageLabel(punto1, "src/Imagenes/punto 2.png");
        SetImageLabel(punto2, "src/Imagenes/punto 4.png");
    }

    private void SetImageLabel(JLabel labelName, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icono = new ImageIcon(
                image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT));
        labelName.setIcon(icono);
        this.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel21 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIdentificacion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtClave = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        txtClave2 = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        btnRegistro = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        Cat4 = new javax.swing.JLabel();
        Dog2 = new javax.swing.JLabel();
        punto2 = new javax.swing.JLabel();
        Dog1 = new javax.swing.JLabel();
        punto3 = new javax.swing.JLabel();
        punto1 = new javax.swing.JLabel();
        Cat3 = new javax.swing.JLabel();
        punto4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(197, 222, 244));
        setSize(new java.awt.Dimension(1240, 500));

        jPanel1.setBackground(new java.awt.Color(197, 222, 244));
        jPanel1.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro");

        txtIdentificacion.setBackground(new java.awt.Color(197, 222, 244));
        txtIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdentificacionActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Identificacion");

        txtNombreUsuario.setBackground(new java.awt.Color(197, 222, 244));
        txtNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreUsuarioActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Nombre");

        txtEmail.setBackground(new java.awt.Color(197, 222, 244));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Email");

        txtClave.setBackground(new java.awt.Color(197, 222, 244));
        txtClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClaveActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Clave");

        txtClave2.setBackground(new java.awt.Color(197, 222, 244));
        txtClave2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClave2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Repetir clave");

        btnRegistro.setBackground(new java.awt.Color(255, 232, 163));
        btnRegistro.setForeground(new java.awt.Color(68, 16, 16));
        btnRegistro.setText("Crear Cuenta");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel4.setText("Tienes una cuenta?,");

        btnLogin.setBackground(new java.awt.Color(255, 166, 41));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(68, 16, 16));
        btnLogin.setText("Iniciar sesion");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtIdentificacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                            .addComponent(txtNombreUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtClave, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtClave2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLogin)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClave2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        Cat4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/huellita de gato 4.png"))); // NOI18N
        jPanel1.add(Cat4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 80, 100));

        Dog2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/huellita perro 2.png"))); // NOI18N
        jPanel1.add(Dog2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, -1, -1));

        punto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/punto 4.png"))); // NOI18N
        jPanel1.add(punto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, -1, -1));

        Dog1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/huellita perro 1.png"))); // NOI18N
        jPanel1.add(Dog1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, -1, -1));

        punto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/punto 4.png"))); // NOI18N
        jPanel1.add(punto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, -1, -1));

        punto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/punto 2.png"))); // NOI18N
        jPanel1.add(punto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, -1, -1));

        Cat3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/huellita gato 2.png"))); // NOI18N
        jPanel1.add(Cat3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, 100));

        punto4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/punto 2.png"))); // NOI18N
        jPanel1.add(punto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 70, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClaveActionPerformed

    private void txtIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdentificacionActionPerformed

    private void txtNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUsuarioActionPerformed

    private void txtClave2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClave2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClave2ActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        Login frmLogin = new Login();
        this.setVisible(false);
        frmLogin.setVisible(true);
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
   // public static void main(String args[]) {
        
       // java.awt.EventQueue.invokeLater(new Runnable() {
         //   public void run() {
              //  new Registro().setVisible(true);
           // }
        //});
    //}
    public static void main(String[] args) {
        File archivo;// para manipular archivos
        FileWriter escribir; //para escribir en el archivo
        PrintWriter linea;//para escribir en el archivo
        String identificacion="";
        String nombre="";
        String email="";
        String clave="";
        String rol="";
        String estado="";
        archivo =new File("Usuario.txt");// preparando el archivo
        if(!archivo.exists()){
            try {
                archivo.createNewFile();
               /* identificacion=JOptionPane.showInputDialog(null, "ingresa el nombre"+
                        "solicitando datos: "+3);
                nombre=JOptionPane.showInputDialog(null, "ingresa el nombre"+
                        "solicitando datos: "+3);
                email=JOptionPane.showInputDialog(null, "ingresa el nombre"+
                        "solicitando datos: "+3); 
                 clave=JOptionPane.showInputDialog(null, "ingresa el nombre"+
                        "solicitando datos: "+3);
                  rol=JOptionPane.showInputDialog(null, "ingresa el nombre"+
                        "solicitando datos: "+3);
                   estado=JOptionPane.showInputDialog(null, "ingresa el nombre"+
                        "solicitando datos: "+3);
                   */escribir=new FileWriter(archivo,true);
                   linea=new PrintWriter(escribir);
                   //escribimos en el archivo
                   linea.print(nombre);
                   linea.print(email);
                   linea.print(clave);
                   linea.print(rol);
                   linea.print(estado);
                   linea.close();
                   escribir.close();
            } catch (IOException ex) {
                Logger.getLogger(Archivos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
             try {
                
                nombre=JOptionPane.showInputDialog(null, "ingresa el nombre"+
                        "solicitando datos: "+3);
                email=JOptionPane.showInputDialog(null, "ingresa el nombre"+
                        "solicitando datos: "+3); 
                 clave=JOptionPane.showInputDialog(null, "ingresa el nombre"+
                        "solicitando datos: "+3);
                  rol=JOptionPane.showInputDialog(null, "ingresa el nombre"+
                        "solicitando datos: "+3);
                   estado=JOptionPane.showInputDialog(null, "ingresa el nombre"+
                        "solicitando datos: "+3);
                   escribir=new FileWriter(archivo,true);
                   linea=new PrintWriter(escribir);
                   //escribimos en el archivo
                   linea.print(nombre);
                   linea.print(email);
                   linea.print(clave);
                   linea.print(rol);
                   linea.print(estado);
                   linea.close();
                   escribir.close();
            } catch (IOException ex) {
                Logger.getLogger(Archivos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cat3;
    private javax.swing.JLabel Cat4;
    private javax.swing.JLabel Dog1;
    private javax.swing.JLabel Dog2;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel punto1;
    private javax.swing.JLabel punto2;
    private javax.swing.JLabel punto3;
    private javax.swing.JLabel punto4;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JPasswordField txtClave2;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
