/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistaAdmin;

import Productos.LeerEscribirArchivo;
import Productos.ListaEnlazada;

import java.io.File;

import java.nio.file.Files;
import java.nio.file.StandardCopyOption;

import javax.swing.JOptionPane;

/**
 *
 * @author Jhonatan
 */
public final class RegistrarProducto extends javax.swing.JFrame {

    String valor;
    LeerEscribirArchivo arch = new LeerEscribirArchivo();
    ListaEnlazada lis = new ListaEnlazada();
    private static final String DATA_FILE = "src/Informacion/Productos.txt";
    private static final String IMAGE_DIRECTORY = "src/Informacion/ImagenesProductos/";
    boolean vacio = false;
    boolean Registro=false;
    /**
     * Creates new form RegistrarProducto
     */
    public RegistrarProducto() {
        initComponents();
        valor = "No seleciono la imagen";
        recuperar();
        jtImagen.setText("No a seleccionado la imagen");
        txtImagenselecionada.setText("No hay imagen seleccionada");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    public void Mensaje(String msg) {
        JOptionPane.showMessageDialog(null, msg);
    }

    public void recuperar() {
        try {
            int archivoVacio = arch.cantidadLineasArchivo(DATA_FILE);
            if (archivoVacio == 0) {
                vacio = true;
            } else {
                vacio = false;
                lis.recuperarArchivo(DATA_FILE);
                System.out.println("entre a recuperar");
            }
        } catch (Exception e) {
            System.out.println("Error al recuperar archivo: " +e);
        }
    }
 
    public void limpiar() {
        jtNombre.setText("");
        jcCategoria.setSelectedIndex(0);
        jcEdad.setSelectedIndex(0);
        jcTipoDeProducto.setSelectedIndex(0);
        jcAnimal.setSelectedIndex(0);
        jcTamaño.setSelectedIndex(0);
        jcColor.setSelectedIndex(0);
        jcTipoEnvio.setSelectedIndex(0);
        jtxDescripcion.setText("");
        jtCodigo.setText("");
        jtCantidad.setText("");
        jtPrecio.setText("");
        jtImagen.setIcon(null);
        valor = "No selecciono la imagen";
        txtImagenselecionada.setText("No hay imagen seleccionada");
        jtImagen.setText(valor);
    }

    public void agregarProducto() {
        int codigo;
        int cantidad;
        double precio;
        if (jtCodigo.getText().equals("") || jtCantidad.getText().equals("") || jtPrecio.getText().equals("")) {
            codigo = 0;
            cantidad = 0;
            precio = 0;
        } else {
            codigo = Integer.parseInt(jtCodigo.getText());
            cantidad = Integer.parseInt(jtCantidad.getText());
            precio = Double.parseDouble(jtPrecio.getText());
        }
        String nombre = jtNombre.getText();
        String categoria = (String) jcCategoria.getSelectedItem();
        String edad = (String) jcEdad.getSelectedItem();
        String tipoDeProducto = (String) jcTipoDeProducto.getSelectedItem();
        String animal = (String) jcAnimal.getSelectedItem();
        String tamano = (String) jcTamaño.getSelectedItem();
        String color = (String) jcColor.getSelectedItem();
        String envio = (String) jcTipoEnvio.getSelectedItem();
        String descripcion = jtxDescripcion.getText();
        if (codigo <= 0 || nombre.equals("") || categoria.equals("Categorias")
                || cantidad <= 0 || edad.equals("Edad") || tipoDeProducto.equals("Tipo De Producto")
                || animal.equals("Animal") || tamano.equals("Tamaño") || color.equals("Color")
                || precio <= 0 || envio.equals("Tipo Envio") || valor.equals("No selecciono la imagen")) {
            JOptionPane.showMessageDialog(null,
                    "Datos incorrectos o incompletos.",
                    "Información",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            String imagen = "";
            int comprados = 0;
            String Descripcion;
            if (descripcion.equals("")) {
                Descripcion = "No hay detalles";
            } else {
                Descripcion = descripcion;
            }
            String Dato = "";
            try {

                if (vacio == true) {
                    //preparar imagen
                    // Crear el directorio de imágenes si no existe
                    File dir = new File(IMAGE_DIRECTORY);
                    if (!dir.exists()) {
                        dir.mkdirs();
                    }
                    String extencion = getFileExtension(valor);
                    imagen = IMAGE_DIRECTORY + codigo + "." + extencion;
                    // Copiar el archivo
                    File sourceFile = new File(valor);
                    File destFile = new File(imagen);
                    Files.copy(sourceFile.toPath(), destFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
                    //agregar directamente
                    Dato = codigo + "&" + nombre + "&" + cantidad + "&" + categoria + "&" + edad + "&" + animal + "&" + color + "&" + tamano + "&" + envio + "&" + precio + "&" + tipoDeProducto + "&" + "vacio" + "&" + imagen + "&" + Descripcion + "&" + comprados;
                    arch.setRutaArchivo(DATA_FILE);
                    arch.guardarArchivo(Dato);
                    Mensaje("Informacion Almacenada");
                    limpiar();
                    lis.recuperarArchivo(DATA_FILE);
                    Registro=true;
                } else {
                    if (lis.codigoexiste(codigo) == true) {
                        Mensaje("El codigo ya existe");
                    } else {
                        //preparar imagen
                        // Crear el directorio de imágenes si no existe
                        File dir = new File(IMAGE_DIRECTORY);
                        if (!dir.exists()) {
                            dir.mkdirs();
                        }
                        String extencion = getFileExtension(valor);
                        imagen = IMAGE_DIRECTORY + codigo + "." + extencion;
                        // Copiar el archivo
                        File sourceFile = new File(valor);
                        File destFile = new File(imagen);
                        Files.copy(sourceFile.toPath(), destFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
                        //agregar directamente
                        Dato = codigo + "&" + nombre + "&" + cantidad + "&" + categoria + "&" + edad + "&" + animal + "&" + color + "&" + tamano + "&" + envio + "&" + precio + "&" + tipoDeProducto + "&" + "vacio" + "&" + imagen + "&" + Descripcion + "&" + comprados;
                        arch.setRutaArchivo(DATA_FILE);
                        arch.guardarArchivo(Dato);
                        Mensaje("Informacion Almacenada");
                        limpiar();
                        lis.recuperarArchivo(DATA_FILE);
                        Registro=true;
                    }   
                }
            } catch (Exception e) {
                System.out.println("Error en archivo");
            }
        }
    }

    private static String getFileExtension(String fileName) {
        if (fileName.lastIndexOf(".") != -1 && fileName.lastIndexOf(".") != 0) {
            return fileName.substring(fileName.lastIndexOf(".") + 1);
        } else {
            return "";  // No se encontró extensión
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtCodigo = new javax.swing.JTextField();
        jtNombre = new javax.swing.JTextField();
        jtCantidad = new javax.swing.JTextField();
        jcCategoria = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jcEdad = new javax.swing.JComboBox<>();
        jcTipoDeProducto = new javax.swing.JComboBox<>();
        jcAnimal = new javax.swing.JComboBox<>();
        jcTamaño = new javax.swing.JComboBox<>();
        jcColor = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jtPrecio = new javax.swing.JTextField();
        jcTipoEnvio = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxDescripcion = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jtImagen = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtImagenselecionada = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setType(java.awt.Window.Type.UTILITY);

        jLabel1.setText("Registrar productos");

        jLabel2.setText("Detalles principales");

        jLabel3.setText("Codigo:");

        jLabel4.setText("Nombre:");

        jLabel6.setText("Cantidad:");

        jcCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Categorias", "Accesorios", "Comodidad", "Cuidado y Aseo", "Juguetes", "Medicamentos", "Vestimenta" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel3)
                        .addGap(83, 83, 83)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, Short.MAX_VALUE)
                .addComponent(jcCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jcEdad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Edad", "Recien Nacido", "Cachorro", "Adolecente", "Joven Adulto", "Adulto", "Senior" }));

        jcTipoDeProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo De Producto", "Masticable", "Fuerza" }));
        jcTipoDeProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcTipoDeProductoActionPerformed(evt);
            }
        });

        jcAnimal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Animal", "Perro", "Gato", "Pez", "Hamster", "Conejo", "Tortuga" }));

        jcTamaño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tamaño", "Pequeño", "Mediano", "Grande" }));

        jcColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Color", "Rojo", "Azul", "Amarrillo", "Verde", "Morado", "Naranja" }));

        jLabel5.setText("Precio:");

        jcTipoEnvio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo Envio", "Envio Gratis", "Envio Expres" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jcColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtPrecio))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jcEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jcTipoDeProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jcAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jcTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jcTipoEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcTipoDeProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcTipoEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jtxDescripcion.setColumns(20);
        jtxDescripcion.setRows(5);
        jScrollPane1.setViewportView(jtxDescripcion);

        jLabel7.setText("Descripcion (opcional)");

        jButton1.setText("Agregar Imagen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtImagenselecionada.setText(".");

        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addGap(120, 120, 120))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(67, 67, 67)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtImagenselecionada, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(35, 35, 35)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jButton2)
                                .addGap(30, 30, 30)
                                .addComponent(jButton3))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(198, 198, 198)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton4))))
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtImagenselecionada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jcTipoDeProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcTipoDeProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcTipoDeProductoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Selecionar_Imagen selecionar = new Selecionar_Imagen(this, true);
        selecionar.setLocationRelativeTo(this);
        valor = selecionar.obtenerValor();
        String condicion = "cancelado";
        // jtImagen.setText(valor);
        if (valor.equals(condicion)) {             
            txtImagenselecionada.setText("Cancelado");
            valor = "No selecciono la imagen";
            jtImagen.setIcon(null);
            jtImagen.setText(valor);
        } else if (valor.equals("")) {  
            txtImagenselecionada.setText("Cancelado");
            valor = "No selecciono la imagen";
            jtImagen.setIcon(null);
            jtImagen.setText(valor);
       } else {
            MostrarImagen mostrar = new MostrarImagen(valor);
            mostrar.MostrarImagen(jtImagen);
            txtImagenselecionada.setText("imagen selecionada");
            
//        Image miImagen = new ImageIcon(valor).getImage();
//        ImageIcon mIcono = new ImageIcon(miImagen.getScaledInstance(jtImagen.getWidth(), jtImagen.getHeight(), Image.SCALE_SMOOTH));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     agregarProducto();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     limpiar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    this.setVisible(false);
    this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarProducto().setVisible(true);
            }
        });
    }
public boolean obtenerValor() {
        this.setVisible(true);
        return Registro;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcAnimal;
    private javax.swing.JComboBox<String> jcCategoria;
    private javax.swing.JComboBox<String> jcColor;
    private javax.swing.JComboBox<String> jcEdad;
    private javax.swing.JComboBox<String> jcTamaño;
    private javax.swing.JComboBox<String> jcTipoDeProducto;
    private javax.swing.JComboBox<String> jcTipoEnvio;
    private javax.swing.JTextField jtCantidad;
    private javax.swing.JTextField jtCodigo;
    private javax.swing.JLabel jtImagen;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtPrecio;
    private javax.swing.JTextArea jtxDescripcion;
    private javax.swing.JLabel txtImagenselecionada;
    // End of variables declaration//GEN-END:variables
}
